language: csharp
solution: AspNetCore.Security.Jwt.sln
mono: none
dist: xenial
dotnet: 2.0
script:
 - dotnet restore
 - dotnet build
 - dotnet test AspNetCore.Security.Jwt.UnitTests/AspNetCore.Security.Jwt.UnitTests/csproj
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1